name: steps_counter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Navigation
  auto_route: ^7.8.3
  
  # Firebase
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7

  # Bloc
  flutter_bloc: ^8.1.3

  # DI
  get_it: ^7.6.4
  
  # UI
  cached_network_image: ^3.3.0
  
  # Rest
  pedometer: ^4.0.1
  shared_preferences: ^2.2.1
  permission_handler: ^11.0.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true